config/routes.rb
Rails.application.routes.draw do
  # Admin interface for managing database:
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Redirect root address to index in tasks controller:
  root to: 'users#welcome'

  post 'tasks/editTask' => 'tasks#edit_task'

  # Handle fetch tasks POST/GET requests from client:
  post 'tasks/fetchTasks' => 'tasks#push_tasks'
  get '/tasks/fetchTasks/task_list_id=:task_list_id' => 'tasks#push_tasks'

  # Handle fetch task lists POST requests from client:
  post 'tasks/fetchLists' => 'tasks#push_lists'

  # Handle delete task POST/GET requests from client:
  post 'tasks/deleteTask' => 'tasks#delete_task'
  get '/tasks/deleteTask/task_id=:task_id' => 'tasks#delete_task'

  # Handle check task POST/GET requests from client:
  post 'tasks/checkTask' => 'tasks#check_task'
  get '/tasks/checkTask/task_id=:task_id(/checked=:checked)' => 'tasks#check_task'

  # Handle POST request for adding task:
  post 'tasks/addTask' => 'tasks#addTask'

  get 'welcome' => 'users#welcome', as: 'welcome'

  get 'login/username=:username(/password=:password)' => 'users#login'
  post 'login' => 'users#login'

  get 'register' => 'users#registerpage'
  post 'users/register' => 'users#register'

  get 'index' => 'tasks#index'
  post 'index' => 'tasks#index'

  post 'task_lists/addList' => 'task_lists#addList'
  post 'task_lists/fetchLists' => 'task_lists#fetchLists'


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
end

app/controllers/tasks_controller.rb
# Controller class for Tasks
class TasksController < ApplicationController
  # Skip CSRF checks [Temporary]
  skip_before_action :verify_authenticity_token

  def edit_task
    @task = Task.find_by_id(params[:task_id])

    if request.post?
      # If updating process is successful
      if @task.update_attribute(:description, params[:task_detail]) and
          @task.update_attribute(:notify, params[:task_notify]) and
          @task.update_attribute(:title, params[:task_title]) and
          @task.update_attribute(:due_date, params[:task_date])
        respond_to do |format|
          format.json {head :no_content}
        end
      else
        respond_to do |format|
          format.json {render status: 400}
        end
      end
    end
  end

  # Handle "fetch tasks" POST/GET requests from client, holds READ in CRUD:
  def push_tasks
    # Find all tasks owned by task list sent by JSON object
    @tasks = Task.where(task_list_id: params[:task_list_id]).all

    # If received request is a GET request (ANDROID INTERFACE)
    if request.get?
      render json: @tasks.to_json
      return
    end

    # If received request is a POST request (WEB INTERFACE)
    if request.post?
      #If a user ID is present, set last used list
      if params[:user_id]
        @user = User.find_by_id(params[:user_id])
        @user.update_attribute(:last_used_list_id, params[:task_list_id])
      end

      # Send all related tasks as an JSON object
      respond_to do |format|
        require 'json'
        format.json {render json: @tasks.to_json}
      end
      return
    end
  end

  # Handle GET requests to index page from client:
  def index
    # Do nothing except rendering the index page
  end

  # Handle "delete task" POST/GET requests from client, holds DELETE in CRUD:
  def delete_task
    # Find the task to be removed whose id is sent in JSON object
    @task = Task.find_by_id(params[:task_id])

    # If received request is a GET request
    if request.get?
      if @task.destroy # If deleting process is successful
        render json: {status: 'success'}
      else # If deleting process is not successful
        render json: {status: 'error'}
      end
      return
    end

    # If received request is a POST request
    if request.post?
      if @task.destroy # If deleting process is successful
        # Send a dummy json object to denote process was successful
        respond_to do |format|
          format.json {head :no_content}
        end
      else # If deleting process is not successful
        # Send an error object to denote process was not successful
        respond_to do |format|
          format.json {render status: 400}
        end
      end
    end
  end

  # Handle "update check status of task" POST requests from client, holds UPDATE in CRUD:
  def check_task
    @task = Task.find_by_id(params[:task_id])

    if request.get?
      if @task.update_attribute(:checked, params[:checked]) # If updating process is successful
        render json: {status: 'success'}
      else # If updating process is not successful
        render json: {status: 'error'}
      end
    end

    # If received request is a POST request
    if request.post?
      if @task.update_attribute(:checked, params[:checked]) # If updating process is successful
        # Send a dummy json object to denote process was successful
        respond_to do |format|
          format.json {head :no_content}
        end
      else # If updating process is not successful
        # Send an error object to denote process was not successful
        respond_to do |format|
          format.json {render status: 400}
        end
      end
    end
  end

  # Handle post request to tasks/addTask for adding new task
  def addTask
    # if task has a title
    if (!params[:task_title].blank?)
      @task = Task.new(:title => params[:task_title],
                       :task_list_id => params[:task_list],
                       :description => params[:task_detail],
                       :due_date => params[:task_due_date],
                       :notify => params[:task_notify],
                       :checked => params[:task_check])
      # if task does not have a title
    else
      @task = Task.new(:title => "Untitled Task",
                       :task_list_id => params[:task_list],
                       :description => params[:task_detail],
                       :due_date => params[:task_due_date],
                       :notify => params[:task_notify],
                       :checked => params[:task_check])
    end

    if @task.save # If adding is successful
      return render json: {status: 'success'}
    else # If adding is not successful
      return render json: {status: 'error'}
    end
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_list_id %>
    <%= form.text_field :task_list_id, id: :task_task_list_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :task_description %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date, id: :task_due_date %>
  </div>

  <div class="field">
    <%= form.label :notify %>
    <%= form.check_box :notify, id: :task_notify %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-animate-top w3-xxlarge" style="display:none;padding-top:50px;background-color:#E6E6FA;width:30% " id="sideMenu">
  <div class="w3-bar-block w3-center" >
    <div id="lists"></div>
    <br>
    <a class="w3-bar-item w3-button w3-text-grey w3-hover-grey" onclick="addList()">Add new</a>
    <a class="w3-bar-item w3-button w3-text-grey w3-hover-grey" onclick="CloseSideMenu()">Close</a>
  </div>
</nav>

<!-- !PAGE CONTENT! -->
<div class="w3-content" style="max-width:1500px">
  <!-- Header -->
  <div class="w3-opacity" id="head1" style="background-color:	#E6E6FA">
    <span class="w3-button w3-xxlarge w3-left" onclick="openSideMenu()"><i class="fa fa-bars"></i></span>
    <div class="w3-clear"></div>
    <header class="w3-center w3-margin-bottom">
      <div class="w3-content w3-row-padding">
        <div class="w3-display-container w3-quarter w3-center">
          <%= image_tag("to_do_list_icon.png", :width=> "50%") %>
        </div>
        <div class="w3-half w3-center">
          <h1><b>TO DO LIST</b></h1>
          <div id="listName"></div>
        </div>
        <div class="w3-quarter w3-display-container w3-display-topright">
          <br>
          <%= link_to image_tag("logout.png", :width => "30%"), welcome_path %>
        </div>
      </div>
    </header>
    <div class="w3-clear"></div>
  </div>
  <br>
  <br>
  <br>
  <!-- Header -->
  <div class="ToDoElement">

  </div>
  <br>
  <br>
  <div class="w3-content  w3-center-right w3-row-padding" style="max-width:1200px;">
    <div class="w3-quarter w3-right w3-opacity">
      <%= image_submit_tag("round-add-button_318-76935.jpg",:onclick=>"document.getElementById('popup').style.display='block'",:width=>"40%",:alt=>"Add") %>
    </div>
  </div>

  <div id="popup" class="w3-modal" style="z-index:4">
    <div class="w3-modal-content w3-animate-zoom">
      <div class="w3-container w3-padding w3-opacity"style="background-color:#008B8B">
        <h2>Add New Task</h2>
      </div>
      <div class="w3-panel w3-opacity">
        <label >Title</label>
        <input id="title" class="w3-input w3-border w3-margin-bottom" type="text">
        <label>Description</label>
        <input id="descr" class="w3-input w3-border w3-margin-bottom" style="height:150px" type="text">
        <label>Due Date</label>
        <input id="date" type="datetime-local" class="w3-input w3-border w3-margin-bottom" type="text">
        <input id="notify" type="checkbox"> Do you want to be notified?</input>
        <div class="w3-row-padding">
          <div class="w3-section w3-right w3-half " >
            <a class="w3-button w3-right" id="addBut" style="background-color:#C0C0C0" >Add</a>
            <br>
          </div>
          <div class="w3-section w3-left w3-half" >
            <a class="w3-button w3-left" id="cancelBut" style="background-color:#C0C0C0" >Cancel</a>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="popup2" class="w3-modal" style="z-index:4">
    <div class="w3-modal-content w3-animate-zoom">
      <div class="w3-container w3-padding w3-opacity"style="background-color:#008B8B">
        <h2>Edit Task</h2>
      </div>
      <div class="w3-panel w3-opacity">
        <label >Title</label>
        <input id="title2" class="w3-input w3-border w3-margin-bottom" type="text">
        <label>Description</label>
        <input id="descr2" class="w3-input w3-border w3-margin-bottom" style="height:150px" type="text">
        <label>Due Date</label>
        <input id="date2" type="datetime-local" class="w3-input w3-border w3-margin-bottom" type="text">
        <input id="notify2" type="checkbox"> Do you want to be notified?</input>
        <div class="w3-row-padding">
          <div class="w3-section w3-right w3-half " >
            <a class="w3-button w3-right" id="editBut" style="background-color:#C0C0C0" >Edit</a>
            <br>
          </div>
          <div class="w3-section w3-left w3-half" >
            <a class="w3-button w3-left" id="cancelBut2" style="background-color:#C0C0C0" >Cancel</a>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="popup3" class="w3-modal" style="z-index:4">
    <div class="w3-modal-content w3-animate-zoom" style="width: 40%">
      <div class="w3-panel w3-opacity" style="padding-top: 20px">
        <label>List Name</label>
        <input id="newlistName" class="w3-input w3-border w3-margin-bottom" type="text">
        <div class="w3-row-padding">
          <div class="w3-section w3-right w3-half " >
            <a class="w3-button w3-right" id="addListBut" style="background-color:#C0C0C0" >Add</a>
            <br>
          </div>
          <div class="w3-section w3-left w3-half" >
            <a class="w3-button w3-left" id="cancelBut3" style="background-color:#C0C0C0" >Cancel</a>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Page Content -->
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var list_id;
    var user_id=localStorage.getItem('user_id');
    var checkedInfo;
    var ToDoThing;
    var toDoTitle;
    var toDoDetail;
    var toDoDate;
    var toDoNotify;
    var num;
    function deleteFunc(n){
        $.ajax({
            type:"POST",
            url:"/tasks/deleteTask",
            data:{device :"web",task_user_id : user_id, task_id : n},
            success:function(data) {
                $("#toDo" + n).remove();
            }
        })
    }
    function showDetail(e){
        $("#detail" + e).toggle();
    }
    function sendCheckedInfo(n){
        checkedInfo=document.getElementById("check"+n).checked;
        $.ajax({
            type:"POST",
            url:"/tasks/checkTask",
            data:{device :"web",task_user_id : user_id,task_id : n, checked:checkedInfo},
            success:function(data) {
                if (checkedInfo == true) {
                    $("#title" + n).css({"text-decoration": "line-through"});
                }
                else {
                    $("#title" + n).css({"text-decoration": "none"});
                }
            }
        })
    }
    function openSideMenu() {
        document.getElementById("sideMenu").style.display = "block";
    }
    function CloseSideMenu() {
        document.getElementById("sideMenu").style.display = "none";
    }
    function editTask(id,tit,det,date,notfy){
        $("#popup2").show();
        document.getElementById("title2").value=tit;
        document.getElementById("descr2").value=det;
        document.getElementById("date2").value=date.substring(0,date.indexOf("Z"));
        if(notfy=="true"){
            document.getElementById("notify2").checked=true;
        }
        else {
            document.getElementById("notify2").checked = false;
        }
        $("#editBut").click(function(){
            var title=document.getElementById("title2").value;
            var detail=document.getElementById("descr2").value;
            var date=document.getElementById("date2").value+"Z";
            console.log(date);
            var notify=document.getElementById("notify2").checked;
            $.ajax({
                type:"POST",
                url:"tasks/editTask",
                data:{device :"web",task_user_id : user_id, task_id : id,task_title : title,task_detail:detail,task_date:date,task_notify:notify},
                success:function(data) {
                    fetchTasks();
                    $("#popup2").hide();
                }
            })
        })
    }
    function fetchLists() {
        $.ajax({
            type:"POST",
            url:"task_lists/fetchLists",
            async: false,
            data:{device :"web",task_user_id : user_id},
            success:function(data){
                $("#lists").empty();
                $("#listName").empty();
                for(num=0;num<data.lists.length;num++){
                    if(data.lastusedList==data.lists[num].id){
                        var lastusedlistname=data.lists[num].title;
                    }
                    var listName=data.lists[num].title;
                    //$("#lists").append("<a class='w3-bar-item w3-button w3-text-grey w3-hover-grey' onclick='selectList(" + data.lists[num].id + ",\"" + listName + "\")'>"+listName +"</a>");
                    $("#lists").append('<a class="w3-bar-item w3-button w3-text-grey w3-hover-grey" onclick="selectList(' + data.lists[num].id + ',\'' + listName +'\')">'+listName +'</a>');

                }
                list_id=data.lastusedList;
                $("#listName").append("<h2><b>"+lastusedlistname+"</b></h2>");
                console.log(data);
            }
        })
    }
    function selectList(m,n){
      list_id=m;
      $("#listName").empty();
      fetchTasks();
      $("#listName").append("<h2><b>"+n+"</b></h2>");
    }
    function addList() {
        $("#popup3").show();
    }
    function fetchTasks(){
        $.ajax({
            type:"POST",
            url:"/tasks/fetchTasks",
            data:{device :"web",user_id : user_id,task_list_id : list_id},
            success:function(data){
                console.log(list_id);
                $(".ToDoElement").empty();
                for(num=0;num<data.length;num++){
                    toDoTitle=data[num].title;
                    toDoDetail=data[num].description;
                    toDoDate=data[num].due_date;
                    toDoNotify=data[num].notify;
                    ToDoThing= "<div id='toDo" + data[num].id + "'><div class= 'w3-content  w3-opacity w3-row-padding w3-center'  style='max-width:1200px ;background-color:#ADD8E6;border-radius:25px;'><div class='w3-quarter w3-center'><br><input type='checkbox' id='check"+data[num].id+"' onclick='sendCheckedInfo("+data[num].id+")' ></div><div class='w3-button w3-half w3-center' style='padding:0px;' id='title"+data[num].id+"' onclick='showDetail("+data[num].id+")'><h2>"+toDoTitle+"</h2></div><div class='w3-quarter w3-center' style='padding:5px;'><h2 class='w3-button' onclick='deleteFunc(" + data[num].id+ ")'><b>X</b></h2></div><div class='w3-panel' id='detail"+data[num].id+"'><p>"+toDoDetail+"</p><p>Due Date: "+toDoDate+"</p><p class='w3-button w3-gray' onclick='editTask(\""+data[num].id+"\",\""+toDoTitle+"\",\""+toDoDetail+"\",\""+toDoDate+"\",\""+toDoNotify+"\")'>Edit</p></div></div><br></dv>";
                    $(".ToDoElement").append(ToDoThing);
                    document.getElementById("check"+data[num].id).checked=data[num].checked;
                    if (data[num].checked== true) {
                        $("#title" + data[num].id).css({"text-decoration": "line-through"});
                    }
                    else {
                        $("#title" + data[num].id).css({"text-decoration": "none"});
                    }
                    $("#detail"+data[num].id).hide();
                }
            }

        })
    }
    $(document).ready(function(){
        fetchLists();
        fetchTasks();
        $("#addBut").click(function(){
            toDoTitle=document.getElementById("title").value;
            toDoDetail=document.getElementById("descr").value;
            toDoDate=document.getElementById("date").value;
            if ($('#notify').is(":checked"))
            {
                toDoNotify=true;
            }
            else{
                toDoNotify=false;
            }
            $.ajax({
                type:"POST",
                url:"/tasks/addTask",
                data:{device :"web",task_user_id : user_id,task_list:list_id,task_title : toDoTitle, task_detail :toDoDetail,task_due_date:toDoDate,task_notify:toDoNotify,task_check:false},
                success:function(data){
                    fetchTasks();
                    $("#popup").hide();
                }
            })
        });
        $("#addListBut").click(function(){
            var lName=document.getElementById("newlistName").value;
            $.ajax({
                type:"POST",
                url:"task_lists/addList",
                data:{device :"web",task_user_id : user_id,list_name:lName},
                success:function(data) {
                    fetchLists();
                    fetchTasks();
                    $("#popup3").hide();
                }
            })
        });
        $("#cancelBut").click(function(){
            $("#popup").hide();
        })
        $("#cancelBut2").click(function(){
            $("#popup2").hide();
        })
        $("#cancelBut3").click(function(){
            $("#popup3").hide();
        })
    });

</script>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task list:</strong>
  <%= @task.task_list %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Notify:</strong>
  <%= @task.notify %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>