config/routes.rb
Rails.application.routes.draw do
  # Admin interface for managing database:
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Redirect root address to index in tasks controller:
  root to: 'users#welcome'

  post 'tasks/editTask' => 'tasks#edit_task'

  # Handle fetch tasks POST/GET requests from client:
  post 'tasks/fetchTasks' => 'tasks#push_tasks'
  get '/tasks/fetchTasks/task_list_id=:task_list_id' => 'tasks#push_tasks'

  # Handle fetch task lists POST requests from client:
  post 'tasks/fetchLists' => 'tasks#push_lists'

  # Handle delete task POST/GET requests from client:
  post 'tasks/deleteTask' => 'tasks#delete_task'
  get '/tasks/deleteTask/task_id=:task_id' => 'tasks#delete_task'

  # Handle check task POST/GET requests from client:
  post 'tasks/checkTask' => 'tasks#check_task'
  get '/tasks/checkTask/task_id=:task_id(/checked=:checked)' => 'tasks#check_task'

  # Handle POST request for adding task:
  post 'tasks/addTask' => 'tasks#addTask'

  get 'welcome' => 'users#welcome', as: 'welcome'

  get 'login/username=:username(/password=:password)' => 'users#login'
  post 'login' => 'users#login'

  get 'register' => 'users#registerpage'
  post 'users/register' => 'users#register'

  get 'index' => 'tasks#index'
  post 'index' => 'tasks#index'

  post 'task_lists/addList' => 'task_lists#addList'
  post 'task_lists/fetchLists' => 'task_lists#fetchLists'


end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :surname, presence: true
  validates :email, presence: true
  validates :username, presence: true
  validates :password, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def login
    @user = User.find_by(username: params[:username], password: params[:password])
    if @user
      if request.get?
        render json: {status: 'success', user_id: @user.id}
      end

      if request.post?
        respond_to do |format|
          require 'json'
          format.json {render json: {status: 'success', user_id: @user.id}}
        end
      end
    else
      if request.get?
        render json: {status: 'error'}
      end

      if request.post?
        respond_to do |format|
          require 'json'
          format.json {render json: {status: 'error'}}
        end
      end
    end
  end

  def welcome
    # Do nothing
  end

  def registerpage
    render 'register'
  end

  def register
    if (params[:username].blank? || params[:password].blank?) ||
        (params[:againpassword].blank? || params[:name].blank?) ||
        (params[:surname].blank? || params[:email].blank?)
      return render json: {status: 'error', msg: 'All fields are required'}
    end

    if User.exists?(username: params[:username])
      return render json: {status: 'error', msg: 'This username is already taken'}
    end

    if params[:password]!=params[:againpassword]
      return render json: {status: 'error', msg: 'Passwords does not match'}
    end

    @user = User.new(username: params[:username],
                     password: params[:password],
                     email: params[:email],
                     name: params[:name],
                     surname: params[:surname])

    if(@user.save)
      return render json: {status: 'success', userid: @user.id}
    else
      return render json: {status: 'error'}
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :user_surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/register.html.erb
<div class="register-page">
  <div class="form">
    <form class="register-form">
      <input type="text" placeholder="username" id="username"/>
      <input type="text" placeholder="email address" id="mail"/>
      <input type="text" placeholder="name" id="name"/>
      <input type="text" placeholder="surname" id="sname"/>
      <input type="password" placeholder="password" id="pass"/>
      <input type="password" placeholder="password" id="againpass"/>
      <button type="button" onclick="register()">register</button>
    </form>
  </div>
</div>
<style>
  @import url(https://fonts.googleapis.com/css?family=Roboto:300);

  .register-page {
    width: 360px;
    padding: 8% 0 0;
    margin: auto;
  }
  .form {
    position: relative;
    z-index: 1;
    background: #FFFFFF;
    max-width: 360px;
    margin: 0 auto 100px;
    padding: 45px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
  }
  .form input {
    font-family: "Roboto", sans-serif;
    outline: 0;
    background: #f2f2f2;
    width: 100%;
    border: 0;
    margin: 0 0 15px;
    padding: 15px;
    box-sizing: border-box;
    font-size: 14px;
  }
  .form button {
    font-family: "Roboto", sans-serif;
    text-transform: uppercase;
    outline: 0;
    background: #3f6b6b;
    width: 100%;
    border: 0;
    padding: 15px;
    color: #FFFFFF;
    font-size: 14px;
    cursor: pointer;
  }
  .form button:hover,.form button:active,.form button:focus {
    background: #4c8484;
  }
  .form .message {
    margin: 15px 0 0;
    color: #b3b3b3;
    font-size: 12px;
  }
  .form .message a {
    color: #4CAF50;
    text-decoration: none;
  }
  .container {
    position: relative;
    z-index: 1;
    max-width: 300px;
    margin: 0 auto;
  }
  .container:before, .container:after {
    content: "";
    display: block;
    clear: both;
  }
  .container .info {
    margin: 50px auto;
    text-align: center;
  }
  .container .info h1 {
    margin: 0 0 15px;
    padding: 0;
    font-size: 36px;
    font-weight: 300;
    color: #1a1a1a;
  }
  .container .info span {
    color: #4d4d4d;
    font-size: 12px;
  }
  .container .info span a {
    color: #000000;
    text-decoration: none;
  }
  .container .info span .fa {
    color: #EF3B3A;
  }
  body {
    background: #E6E6FA; /* fallback for old browsers */
    font-family: "Roboto", sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>
  function register() {
      var username=document.getElementById("username").value;
      var name=document.getElementById("name").value;
      var surname=document.getElementById("sname").value;
      var password=document.getElementById("pass").value;
      var againpass=document.getElementById("againpass").value;
      var email=document.getElementById("mail").value;
      $.ajax({
          type:"POST",
          url:"/users/register",
          data:{device :"web",username:username,name:name,surname:surname,password: password,againpassword: againpass,email:email},
          success:function(data) {
              console.log(data)
              if(data.status=="success") {
                  window.location = "/";
              }
          }

      })
  }
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/welcome.html.erb
<div class="login-page">
  <div class="form">
    <form class="login-form">
      <input type="text" placeholder="username" id="username"/>
      <input type="password" placeholder="password" id="pass"/>
      <button type="button" onclick="login()">login</button>
      <br>
      <p>If you do not have an account register</p>
      <button type="button" onclick="register()">register</button>
    </form>
  </div>
</div>
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);

.login-page {
width: 360px;
padding: 8% 0 0;
margin: auto;
}
.form {
position: relative;
z-index: 1;
background: #FFFFFF;
max-width: 360px;
margin: 0 auto 100px;
padding: 45px;
text-align: center;
box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
font-family: "Roboto", sans-serif;
outline: 0;
background: #f2f2f2;
width: 100%;
border: 0;
margin: 0 0 15px;
padding: 15px;
box-sizing: border-box;
font-size: 14px;
}
.form button {
font-family: "Roboto", sans-serif;
text-transform: uppercase;
outline: 0;
background: #3f6b6b;
width: 100%;
border: 0;
padding: 15px;
color: #FFFFFF;
font-size: 14px;
cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
background: #4c8484;
}
.form .message {
margin: 15px 0 0;
color: #b3b3b3;
font-size: 12px;
}
.form .message a {
color: #4CAF50;
text-decoration: none;
}
.container {
position: relative;
z-index: 1;
max-width: 300px;
margin: 0 auto;
}
.container:before, .container:after {
content: "";
display: block;
clear: both;
}
.container .info {
margin: 50px auto;
text-align: center;
}
.container .info h1 {
margin: 0 0 15px;
padding: 0;
font-size: 36px;
font-weight: 300;
color: #1a1a1a;
}
.container .info span {
color: #4d4d4d;
font-size: 12px;
}
.container .info span a {
color: #000000;
text-decoration: none;
}
.container .info span .fa {
color: #EF3B3A;
}
body {
background: #E6E6FA; /* fallback for old browsers */
font-family: "Roboto", sans-serif;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>
  function login(){
      var username=document.getElementById("username").value;
      var password=document.getElementById("pass").value;
      $.ajax({
          type:"POST",
          url:"login",
          async:false,
          data:{device :"web",username:username,password:password},
          success:function(data) {
              if(data.status=="success") {
                  localStorage.setItem('user_id', data.user_id);
                  window.location = "/index";
              }
              else{
                  alert("Mistake in username or in password");
              }
          }
      })
  }
  function register() {
      window.location ="/register";
  }
</script>