config/routes.rb
Rails.application.routes.draw do
  # Admin interface for managing database:
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Redirect root address to index in tasks controller:
  root to: 'users#welcome'

  post 'tasks/editTask' => 'tasks#edit_task'

  # Handle fetch tasks POST/GET requests from client:
  post 'tasks/fetchTasks' => 'tasks#push_tasks'
  get '/tasks/fetchTasks/task_list_id=:task_list_id' => 'tasks#push_tasks'

  # Handle fetch task lists POST requests from client:
  post 'tasks/fetchLists' => 'tasks#push_lists'

  # Handle delete task POST/GET requests from client:
  post 'tasks/deleteTask' => 'tasks#delete_task'
  get '/tasks/deleteTask/task_id=:task_id' => 'tasks#delete_task'

  # Handle check task POST/GET requests from client:
  post 'tasks/checkTask' => 'tasks#check_task'
  get '/tasks/checkTask/task_id=:task_id(/checked=:checked)' => 'tasks#check_task'

  # Handle POST request for adding task:
  post 'tasks/addTask' => 'tasks#addTask'

  get 'welcome' => 'users#welcome', as: 'welcome'

  get 'login/username=:username(/password=:password)' => 'users#login'
  post 'login' => 'users#login'

  get 'register' => 'users#registerpage'
  post 'users/register' => 'users#register'

  get 'index' => 'tasks#index'
  post 'index' => 'tasks#index'

  post 'task_lists/addList' => 'task_lists#addList'
  post 'task_lists/fetchLists' => 'task_lists#fetchLists'


end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  #before_action :set_task_list, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def fetchLists
    @lists = TaskList.where(user_id: params[:task_user_id])
    @user = User.find_by(id: params[:task_user_id])
    return render json: {status: 'success', lists: @lists,
                         'lastusedList': @user.last_used_list_id}
  end

  def addList
    if params[:list_name].blank?
      return render json: {status: 'error'}
    end

    @task_list = TaskList.new(user_id: params[:task_user_id],
                              title: params[:list_name])
    if @task_list.save
      @user = User.find_by_id(params[:task_user_id])
      @user.update_attribute(:last_used_list_id, @task_list.id)
      return render json: {status: 'success'}
    end

    return render json: {status: 'error'}
  end

end

app/helpers/task_list_helper.rb
module TaskListHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
<%= form_with(model: task_list, local: true) do |form| %>
  <% if task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_list_title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :task_list_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.title %></td>
        <td><%= task_list.user %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task List', new_task_list_path %>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task_list.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @task_list.user %>
</p>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>